title: e11iptic
description: e11iptic is a community of contributors in security research and verifiable compute.

baseurl: ""
url: "https://e11iptic.github.io"
theme: minima
plugins:
  - jekyll-feed
